export const Tasklist_NIH_R = [
  {
    'Form/File': 'SF424(R&R) Project/Performance Site Locations',
    Section: '',
    Component: 'Sites',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'SF424(R&R) Other Project Information',
    Section: '',
    Component: 'Project Summary/Abstract (30 lines)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Project Narrative (3 sentences)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Bibliography & Refs cited',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Facilities and Other Resources',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Equipment',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'SF424(R&R) Senior/Key Person Profile',
    Section: '',
    Component: 'Biosketches for key personnel: please include in the following order as applicable',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Contact PI MPI Co-I Other key personnel',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'R&R Budget',
    Section: '',
    Component: 'Budget',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Budget Justification:',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'R&R Subaward Budget',
    Section: '',
    Component: 'Consortium insitution(s):',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'PHS 398 Cover Page Supplement',
    Section: '',
    Component: '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'PHS 398 Research Plan Form',
    Section: '',
    Component: 'Introduction to Application (For Resubmission and Revision Application) - 1 page',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Specific Aims -1 page',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component:
      'Research Strategy -(12 pages for R01, R21/R33 etc.; 6 pages for R03, R35, R36, etc.)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Progress Report Publication List (For Renewal)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Other Plan(s)',
    Component: 'Data Management and Sharing Plan',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Consortium/Contractual Arrangements (if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Vertebrate Animals (if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Multiple PD/PI Leadership Plan (if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Letters of Support (if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Resource Sharing Plan (brief 1-paragraph description)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Appendix',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File':
      'PHS Human Subjects and Clinical Trials Information Form (no page limits for any attachments in this form)  Complete Section 1-3 if non-clinical trial; Complete all sections if clinical trial.',
    Section: 'Section 1 – Basic Information',
    Component: 'Study Title (text; 600 characters) Clinical Trial Questionnaire',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Section 2 - Study Population Characteristics',
    Component: 'Eligibility Criteria (text; 15,000 characters max)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Inclusion of Individuals Across the Lifespan (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Inclusion of Women, Minorities (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Targeted/Planned Enrollment Table',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Recruitment and Retention Plan (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Study Timeline (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Enrollment of First Subject',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Section 3 - Protection and Monitoring Plans',
    Component: 'Protection of Human Subjects (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Single IRB plan for multi-site study',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Data and Safety Monitoring Plan (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Overall Structure of the Study Team (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Section 4 - Protocol Synopsis',
    Component: 'Narrative Study Description (text; 32,000 characters max)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component:
      'Interventions Description (text; name, 200 characters max; description, 1,000 characters max; can include up to 20 interventions)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Measures (999 characters max per measure)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Statistical Design and Power (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Subject Participation Duration (text; 255 characters max)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Is this an applicable clinical trial under FDAAA?',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Dissemination Plan (PDF)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Section 5 – Other Clinical Trial-related Attachments',
    Component: 'Milestone Plan (The filename "Milestone Plan.pdf" must be used, if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
]
