export const Tasklist_HRSA = [
  {
    'Form/File': '',
    Section: '',
    Component:
      'Biosketches and Other Support for key personnel: please include in the following order as applicable',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Contact PI MPI Co-I Other key personnel',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Project Abstract',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Project Narrative',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Budget',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Budget Narrative',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'Attachments',
    Section: '',
    Component: 'Work Plan',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Staffing Plan and Job',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Biographical sketches',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Agreements with other entities',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Multi-year budget (Fifth Year)',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Project organizational chart',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Tables and charts',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Proof of non-profit status',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Progress report for competing continuation applicants',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Indirect cost agreement',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Other relevant documents (list below)',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'Other Required Forms',
    Section: '',
    Component: 'Application for Federal Assistance',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Budget Information for Non-Construction Programs (SF-424A)',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Disclosure of Lobbying Activites (SF_LLL), optional',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Project/Performance Site',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Grants.gov Lobbying Form',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Key Contacts',
    'Included in Page Limit?': '',
    'Number of Pages': '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
]
