export const Tasklist_NIH_T = [
  {
    'Form/File': 'SF424(R&R) Project/Performance Site Locations',
    Section: '',
    Component: 'Sites',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'SF424(R&R) Other Project Information',
    Section: '',
    Component: 'Project Summary/Abstract (30 lines)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Project Narrative (3 sentences)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Bibliography & Refs cited',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Facilities and Other Resources',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Equipment',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'SF424(R&R) Senior/Key Person Profile',
    Section: '',
    Component: 'Biosketches for key personnel: please include in the following order as applicable',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Contact PI Multi PI Co-Investigator Other key personnel',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'R&R Budget',
    Section: '',
    Component: 'Budget',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Budget Justification:',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'R&R Subaward Budget',
    Section: '',
    Component: 'Consortium insitution(s):',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'PHS 398 Cover Page Supplement',
    Section: '',
    Component: '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'PHS 398 Training Program Plan',
    Section: 'Introduction',
    Component:
      'Introduction to Application (For Resubmission and Revision Application) - (3 pages for Resubmission and 1 page for Revision)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Training Program Section',
    Component: 'Program Plan - 25 pages',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Recruitment Plan to Enhance Diversity - 3 pages',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Plan for Instruction in the Responsible Conduct of Research - 3 pages',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Plan for Instruction in Methods for enhancing Reproducibility - 3 pages',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Multiple PD/PI Leadership Plan (if Applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component:
      'Progress Report  (For Renewal Applications) - 5 pages for a program overview and 1 page for each appointee to the grant',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Faculty, Trainees and Training Record Section',
    Component: 'Participating Faculty Biosketches',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Letters of Support',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Data Tables',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Other Plan(s)',
    Component: 'Data Management and Sharing Plan',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Consortium/Contractual Arrangements (if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Vertebrate Animals (if applicable)',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Appendix',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
]
