export const defaultTasklist = [
  {
    formFile: '',
    section: '',
    component: 'Contact PI',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'MPI',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'Co-I',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'Other key personnel',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'Budget',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'Budget Justification',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'Abstract',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
  {
    formFile: '',
    section: '',
    component: 'Research Plan',
    personResponsible: '',
    dateDue: '',
    status: '',
    finalFileLocation: '',
  },
]
