export const defaultTasklist = [
  {
    formFile: 'SF424(R&R)',
    section: 'Project/Performance Site Locations',
    component: 'UIC, Wash U',
    personResponsible: 'Jeanne/Cheryl',
    status: 'Final',
  },
  {
    formFile: 'SF424(R&R)',
    section: 'Other Project Information',
    component: 'Project Summary/Abstract',
    personResponsible: 'Jeanne',
    status: 'Final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\PDF',
  },
  {
    formFile: 'SF424(R&R)',
    section: 'Other Project Information',
    component: 'Project Narrative',
    personResponsible: 'Jeanne',
    status: 'Final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\PDF',
  },
  {
    formFile: 'SF424(R&R)',
    section: 'Other Project Information',
    component: 'Bibliography & Refs cited',
    personResponsible: 'Jeanne',
    status: 'Final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\PDF',
  },
  {
    formFile: 'SF424(R&R)',
    section: 'Other Project Information',
    component: 'Facilities and Other Resources',
    personResponsible: 'Jeanne',
    status: 'Final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\PDF',
  },
  {
    formFile: 'SF424(R&R)',
    section: 'Senior/Key Person Profile',
    component:
      'Biosketches for key personnel: Jun Ma, MPI, Contact PI, Thomas Kannampallil (MPI) at Wash U, Colin Goodman, Co-I/study MD, UIC, Daphne Lew, Biostatistician, Wash U',
    personResponsible: 'Jeanne',
    status: 'All final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\Bios',
  },
  {
    formFile: 'R&R Budget',
    section: 'Budget',
    component: 'Budget Justification',
    personResponsible: 'Jeanne/Cheryl',
    status: 'Drafted',
  },
  {
    formFile: 'R&R Subaward Budget',
    section: 'Consortium Institutions',
    component: 'Wash U',
    personResponsible: 'Jeanne/Cheryl',
    status: 'Need WashU doc',
  },
  {
    formFile: 'PHS 398 Research Plan Form',
    section: 'Specific Aims',
    component: 'Specific Aims',
    personResponsible: 'Jeanne',
    status: 'Final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\PDF',
  },
  {
    formFile: 'PHS 398 Research Plan Form',
    section: 'Other Plan(s)',
    component: 'Data Management and Sharing Plan',
    personResponsible: 'Jeanne',
    status: 'Final',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\PDF',
  },
  {
    formFile: 'New PHS Human Subjects and Clinical Trials Information Form',
    section: 'Section 1 – Basic Information',
    component: 'Study Title (text; 600 characters)',
    personResponsible: 'Nan',
    status: 'Entered',
  },
  {
    formFile: 'New PHS Human Subjects and Clinical Trials Information Form',
    section: 'Section 2 - Study Population Characteristics',
    component: 'Eligibility Criteria (text; 15,000 characters max)',
    personResponsible: 'Nan',
    status: 'Final - Entered',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\Word',
  },
  {
    formFile: 'New PHS Human Subjects and Clinical Trials Information Form',
    section: 'Section 4 - Protocol Synopsis',
    component: 'Narrative Study Description (text; 32,000 characters max)',
    personResponsible: 'Nan',
    status: 'Final - Entered',
    finalFileLocation: 'Box\\Level Up NIDDK Small R01\\FINAL DOCS\\Word',
  },
  // Add remaining rows here...
]
