export const Tasklist_DOD = [
  {
    'Form/File': 'SF424(R&R) Senior/Key Person Profile',
    Section: '',
    Component:
      'Biosketches and Other Support for key personnel: please include in the following order as applicable',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Contact PI MPI Co-I Other key personnel',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'R&R Budget',
    Section: '',
    Component: 'Budget',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: 'Budget Justification:',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'R&R Subaward Budget',
    Section: '',
    Component: 'Consortium insitution(s):',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: '',
    Component: '',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': 'Attachment Form',
    Section: 'Attachment 1',
    Component: 'ProjectNarrative.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 2',
    Component: 'Support.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 3',
    Component: 'TechAbs.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 4',
    Component: 'LayAbs.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 5',
    Component: 'SOW.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 6',
    Component: 'Impact.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 7',
    Component: 'AnimalResPlan.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
  {
    'Form/File': '',
    Section: 'Attachment 8',
    Component: 'RequiredReps.pdf',
    'Person Responsible': '',
    'Date Due': '',
    'Status/Comments': '',
    'Final file location': '',
  },
]
